name: CI/CD Deployment with SSH

on:
  push:
    branches:
      - qa       # Rama para QA (pruebas)
      - main     # Rama para producción

jobs:
  deploy-qa:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to QA instance
        run: |
          scp -o StrictHostKeyChecking=no -r ./index.html ec2-user@<DIRECCION_PUBLICA_EC2_QA>:/var/www/html
          ssh -o StrictHostKeyChecking=no ec2-user@<DIRECCION_PUBLICA_EC2_QA> "sudo systemctl restart httpd"

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to production instances
        run: |
          # Instancia 1
          scp -i /path/to/your/key.pem -o StrictHostKeyChecking=no -r ./index.html ec2-user@54.173.227.170:/var/www/html/
          ssh -o StrictHostKeyChecking=no ec2-user@54.173.227.170 "sudo systemctl restart httpd"

          # Instancia 2
          scp -i /path/to/your/key.pem -o StrictHostKeyChecking=no -r ./index.html ec2-user@34.207.111.76:/var/www/html/
          ssh -o StrictHostKeyChecking=no ec2-user@34.207.111.76 "sudo systemctl restart httpd"

          # Instancia 3
          scp -i /path/to/your/key.pem -o StrictHostKeyChecking=no -r ./index.html ec2-user@44.220.71.163:/var/www/html/
          ssh -o StrictHostKeyChecking=no ec2-user@44.220.71.163 "sudo systemctl restart httpd"


