name: CI/CD Deployment with SSH

on:
  push:
    branches:
      - qa       # Rama para QA (pruebas)
      - main     # Rama para producción

jobs:
  deploy-qa:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to QA instance
        run: |
          scp -o StrictHostKeyChecking=no -r ./index.html ec2-user@3.84.201.212:/var/www/html
          ssh -o StrictHostKeyChecking=no ec2-user@3.84.201.212 "sudo systemctl restart httpd"

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

